# Generated by Django 4.0.5 on 2023-05-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
