# Generated by Django 4.0.5 on 2023-05-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cuantity_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dolar_blue',
            field=models.FloatField(default=0),
        ),
    ]
