# Generated by Django 4.0.5 on 2023-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_dolar_blue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dolar_blue',
            new_name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='total_USD',
            field=models.FloatField(default=0),
        ),
    ]
